[[redirects]]
  from = "/products"
  to = "/"
  status = 200

[[redirects]]
  from = "/products/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/"
  status = 200

[[redirects]]
  from = "/order-confirmation"
  to = "/"
  status = 200